name: Publish Satis Repo

on:
  workflow_dispatch:
    inputs:
      repository-url:
        required: false
        description: URL of repository to update
      verbosity:
        type: choice
        description: Verbose Level
        options: 
        - normal
        - verbose
        - very_verbose
      skip-cache:
        type: boolean
        description: Do you want to skip saved cache?
      fresh:
        type: boolean
        description: Do you want fully recreate repository from scratch?
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure composer auth
      run: composer config -g github-oauth.github.com ${{secrets.COMPOSER_TOKEN}}

    - name: Satis Cache
      uses: actions/cache@v3
      if: inputs.skip_cache == false
      with:
        path: satis-cache
        key: satis-${{ runner.os }}-${{ github.run_id }}
        restore-keys: satis-${{ runner.os }}
        
    - name: Build Satis Repo
      uses: kduma-OSS/GH-build-s3-satis-action@v2
      with:
        repository-url: ${{ inputs.repository-url }}
        verbosity: ${{ inputs.verbosity }}
        use-cache: ${{ !(inputs.skip-cache == true) }}
        fresh: ${{ inputs.fresh == true }}
        
        s3-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
        s3-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        s3-region: ${{ vars.S3_REGION }}
        s3-bucket: ${{ vars.S3_BUCKET }}
        s3-endpoint: ${{ vars.S3_ENDPOINT }}
